### ISSUE TITLE
Question: Best practice to view structured logs

### ISSUE THREAD

**Issue by ciaoben** [thanpolas/logality#11]
Is it more a general question rather than relative to this library, but since I am adding this library to my new project I would like to understand better a thing:

```
{"level":"warn","severity":4,"dt":"2020-07-03T10:33:11.107Z","message":"Details of not found player:","context":{"runtime":{"application":"Logality"},"source":{"file_name":"/config/log.js"},"system":{"hostname":"MacBook-Pro-di-Nicolo.local","pid":58853,"process_name":"/usr/local/bin/node"},"custom":{"team_result":"L"}},"event":{}}
{"level":"warn","severity":4,"dt":"2020-07-03T10:33:11.107Z","message":"------------------------------------------------","context":{"runtime":{"application":"Logality"},"source":{"file_name":"/config/log.js"},"system":{"hostname":"MacBook-Pro-di-Nicolo.local","pid":58853,"process_name":"/usr/local/bin/node"}},"event":{}}
```

This is an example of the output of this log library with default configuration. What is the best way to format logs in a more "human" format (as the image on the readme) while keeping this detailed structured log??
 (basically only visualize logs in more friendly way when `tail -f` on the server)

**Comment by thanpolas** [comment]
There are two ways I can think of that can work out of the box:

## During Development

Use the `preetyPrint` [configuration option](https://github.com/thanpolas/logality#initial-configuration) when initializing logality. That is what was used to take the screenshot that you are referring to. This is used for local development only to aid the developer and should not be used in production.

## In Production tail -f

To view the raw JSON logs in a human readable manner, using only unix tools, the best recommendation I have for you is to check the [jq](https://stedolan.github.io/jq/) package that does exactly that, it parses JSON streams.

The more involved, and ultimate solution is to have an appropriate stack or service that accepts and parses the JSON logs so you can create your dashboards and specific queries.

**Comment by ciaoben** [comment]
Thank you very much, this was perfectly clear! 🙏
